import { PostJournalCommand } from "../../accounting/application/journal-repository";
import { JournalPostingService } from "../../accounting/application/journal-posting-service";
import { CashEngine } from "../domain/cash-engine";
import { CashError, CashValidationContext, TenantContext } from "../domain/cash-types";
import { CashRepository, CloseSessionCommand, OpenSessionCommand, ReconcileCashCommand, RecordCashMovementCommand, TransferCashCommand } from "./cash-repository";

export class CashService {
  constructor(private readonly repo: CashRepository, private readonly journal: JournalPostingService, private readonly engine = new CashEngine()) {}
  async openSession(command: OpenSessionCommand) { const ctx = this.ctx(command); const drawer = await this.repo.findDrawer(ctx, command.drawerId); if (await this.repo.findOpenSessionByDrawer(ctx, command.drawerId)) throw new CashError("SESSION_ALREADY_OPEN", "Cash drawer already has an open session."); const accounts = await this.repo.findAccounts(ctx, [drawer?.cashAccountId, command.equityAccountId].filter((id): id is string => Boolean(id))); const byId = new Map(accounts.map((a) => [a.id, a])); const preview = this.engine.previewOpen(command, { drawer, cashAccount: drawer ? byId.get(drawer.cashAccountId) ?? null : null, equityAccount: byId.get(command.equityAccountId) ?? null }); const posted = await this.post(ctx, command.openedAt, "CASH_OPENING_BALANCE", command.drawerId, preview.description, preview.lines, "cash-open:" + ctx.businessId + ":" + command.drawerId + ":" + command.openedAt.toISOString()); const session = await this.repo.createSession(ctx, command, drawer!.cashAccountId); await this.repo.createMovement(ctx, { ...command, type: "OPENING_BALANCE", movementDate: command.openedAt, cashAccountId: drawer!.cashAccountId, amount: command.openingAmount, description: "Opening balance" }, "OPENING_BALANCE", drawer!.cashAccountId, command.openingAmount, posted.journalId); await this.audit(ctx, "CASH_SESSION_OPENED", "cash_session", session.id, { openingAmount: command.openingAmount.toString() }); return { session, journal: posted, preview }; }
  async recordCashMovement(command: RecordCashMovementCommand) { const ctx = this.ctx(command); const validation = await this.context(ctx, command.cashAccountId, command.sessionId, command.categoryAccountId); const preview = this.engine.previewMovement(command, validation); const posted = await this.post(ctx, command.movementDate, "CASH_" + command.type, command.sessionId ?? command.cashAccountId, command.description, preview.lines, "cash-move:" + ctx.businessId + ":" + (command.sessionId ?? "no-session") + ":" + command.type + ":" + command.movementDate.toISOString() + ":" + command.amount.toString()); const movement = await this.repo.createMovement(ctx, command, command.type, command.cashAccountId, command.amount, posted.journalId); if (command.sessionId) { const session = validation.session!; await this.repo.updateSessionExpected(ctx, session.id, this.engine.expectedAfter(command.type, session.expectedClosingAmount, command.amount)); } await this.audit(ctx, "CASH_MOVEMENT_RECORDED", "cash_movement", movement.id, { type: command.type, amount: command.amount.toString() }); return { movement, journal: posted, preview }; }
  async transferCash(command: TransferCashCommand) { const ctx = this.ctx(command); const accounts = await this.repo.findAccounts(ctx, [command.sourceCashAccountId, command.destinationCashAccountId]); const byId = new Map(accounts.map((a) => [a.id, a])); const session = command.sessionId ? await this.repo.findSession(ctx, command.sessionId) : null; const preview = this.engine.previewTransfer(command, { session, cashAccount: byId.get(command.sourceCashAccountId) ?? null, destinationCashAccount: byId.get(command.destinationCashAccountId) ?? null }); const posted = await this.post(ctx, command.movementDate, "CASH_TRANSFER", command.sessionId ?? command.sourceCashAccountId, command.description, preview.lines, "cash-transfer:" + ctx.businessId + ":" + command.sourceCashAccountId + ":" + command.destinationCashAccountId + ":" + command.movementDate.toISOString() + ":" + command.amount.toString()); const movement = await this.repo.createMovement(ctx, command, "TRANSFER", command.sourceCashAccountId, command.amount, posted.journalId, command.destinationCashAccountId); if (command.sessionId && session) await this.repo.updateSessionExpected(ctx, session.id, this.engine.expectedAfter("TRANSFER", session.expectedClosingAmount, command.amount)); await this.audit(ctx, "CASH_TRANSFER_RECORDED", "cash_movement", movement.id, { amount: command.amount.toString() }); return { movement, journal: posted, preview }; }
  async closeSession(command: CloseSessionCommand) { const ctx = this.ctx(command); const session = await this.repo.findSession(ctx, command.sessionId); const accounts = await this.repo.findAccounts(ctx, [session?.cashAccountId, command.differenceAccountId].filter((id): id is string => Boolean(id))); const byId = new Map(accounts.map((a) => [a.id, a])); const result = this.engine.previewClose(command, { session, cashAccount: session ? byId.get(session.cashAccountId) ?? null : null, differenceAccount: byId.get(command.differenceAccountId) ?? null }); const posted = result.preview ? await this.post(ctx, command.closedAt, "CASH_CLOSING_DIFFERENCE", command.sessionId, result.preview.description, result.preview.lines, "cash-close:" + ctx.businessId + ":" + command.sessionId + ":" + command.closedAt.toISOString()) : null; const closed = await this.repo.closeSession(ctx, command.sessionId, command, result.differenceAmount); await this.repo.createMovement(ctx, { ...command, type: "CLOSING", movementDate: command.closedAt, cashAccountId: session!.cashAccountId, amount: command.countedAmount, description: "Closing cash" }, "CLOSING", session!.cashAccountId, command.countedAmount, posted?.journalId ?? ""); await this.audit(ctx, "CASH_SESSION_CLOSED", "cash_session", closed.id, { countedAmount: command.countedAmount.toString(), differenceAmount: result.differenceAmount.toString() }); return { session: closed, journal: posted, preview: result.preview }; }
  async reconcileCash(command: ReconcileCashCommand) { const ctx = this.ctx(command); const session = await this.repo.findSession(ctx, command.sessionId); const accounts = await this.repo.findAccounts(ctx, [session?.cashAccountId, command.differenceAccountId].filter((id): id is string => Boolean(id))); const byId = new Map(accounts.map((a) => [a.id, a])); const result = this.engine.previewReconcile(command, { session, cashAccount: session ? byId.get(session.cashAccountId) ?? null : null, differenceAccount: byId.get(command.differenceAccountId) ?? null }); const posted = result.preview ? await this.post(ctx, command.reconciledAt, "CASH_RECONCILIATION", command.sessionId, result.preview.description, result.preview.lines, "cash-reconcile:" + ctx.businessId + ":" + command.sessionId + ":" + command.reconciledAt.toISOString()) : null; const rec = await this.repo.createReconciliation(ctx, command, session!.expectedClosingAmount, result.differenceAmount, posted?.journalId ?? null); await this.audit(ctx, "CASH_RECONCILED", "cash_reconciliation", rec.id, { differenceAmount: result.differenceAmount.toString() }); return { reconciliation: rec, journal: posted, preview: result.preview }; }
  private async context(ctx: TenantContext, cashAccountId: string, sessionId?: string, categoryAccountId?: string): Promise<CashValidationContext> { const [session, accounts] = await Promise.all([sessionId ? this.repo.findSession(ctx, sessionId) : Promise.resolve(null), this.repo.findAccounts(ctx, [cashAccountId, categoryAccountId].filter((id): id is string => Boolean(id)))]); const byId = new Map(accounts.map((a) => [a.id, a])); return { session, cashAccount: byId.get(cashAccountId) ?? null, categoryAccount: categoryAccountId ? byId.get(categoryAccountId) ?? null : null }; }
  private async post(ctx: TenantContext, date: Date, source: string, sourceId: string, description: string, lines: PostJournalCommand["lines"], idempotencyKey: string) { const cmd: PostJournalCommand = { businessId: ctx.businessId, actorUserId: ctx.actorUserId, transactionDate: date, source, sourceId, description, idempotencyKey, lines: lines.map((line) => ({ accountId: line.accountId, side: line.side, amount: line.amount })) }; if (ctx.requestId !== undefined) cmd.requestId = ctx.requestId; if (ctx.ipAddress !== undefined) cmd.ipAddress = ctx.ipAddress; if (ctx.userAgent !== undefined) cmd.userAgent = ctx.userAgent; return this.journal.post(cmd); }
  private async audit(ctx: TenantContext, action: Parameters<CashRepository["createAuditLog"]>[1]["action"], entityType: Parameters<CashRepository["createAuditLog"]>[1]["entityType"], entityId: string, metadata: Record<string, unknown>) { await this.repo.createAuditLog(ctx, { action, businessId: ctx.businessId, actorUserId: ctx.actorUserId, entityType, entityId, metadata }); }
  private ctx(command: { businessId: string; actorUserId: string; requestId?: string; ipAddress?: string; userAgent?: string }): TenantContext { const ctx: TenantContext = { businessId: command.businessId, actorUserId: command.actorUserId }; if (command.requestId !== undefined) ctx.requestId = command.requestId; if (command.ipAddress !== undefined) ctx.ipAddress = command.ipAddress; if (command.userAgent !== undefined) ctx.userAgent = command.userAgent; return ctx; }
}
