import { Prisma, PrismaClient } from "@prisma/client";
import { CreateAttractionInput, CreateParkingServiceInput, CreateRentalServiceInput, CreateTenantRentalInput, CreateTicketPackageInput, CreateTicketTypeInput, CreateVisitorTransactionInput, TenantContext, VisitorTransaction } from "../domain/tourism-types";
import { TourismAuditEvent, TourismRepository } from "../application/tourism-repository";

export class PrismaTourismRepository implements TourismRepository {
  constructor(private readonly prisma: PrismaClient) {}
  async createAttraction(ctx: TenantContext, input: CreateAttractionInput) { const r = await this.prisma.attraction.create({ data: { businessId: ctx.businessId, name: input.name, description: input.description ?? null, location: input.location ?? null, visitorLimit: input.visitorLimit ?? null, startsOn: input.startsOn ?? null, endsOn: input.endsOn ?? null } }); return r; }
  async createTicketType(ctx: TenantContext, input: CreateTicketTypeInput) { return this.prisma.ticketType.create({ data: { businessId: ctx.businessId, attractionId: input.attractionId, name: input.name, revenueCategoryId: input.revenueCategoryId, dailyPrice: input.dailyPrice, weekendPrice: input.weekendPrice ?? null, seasonalPrice: input.seasonalPrice ?? null, seasonalStartsOn: input.seasonalStartsOn ?? null, seasonalEndsOn: input.seasonalEndsOn ?? null, visitorLimit: input.visitorLimit ?? null, startsOn: input.startsOn ?? null, endsOn: input.endsOn ?? null } }); }
  async createTicketPackage(ctx: TenantContext, input: CreateTicketPackageInput) { return this.prisma.ticketPackage.create({ data: { businessId: ctx.businessId, attractionId: input.attractionId, name: input.name, revenueCategoryId: input.revenueCategoryId, packagePrice: input.packagePrice, maxVisitors: input.maxVisitors ?? null, startsOn: input.startsOn ?? null, endsOn: input.endsOn ?? null } }); }
  async createParkingService(ctx: TenantContext, input: CreateParkingServiceInput) { return this.prisma.parkingService.create({ data: { businessId: ctx.businessId, attractionId: input.attractionId, name: input.name, revenueCategoryId: input.revenueCategoryId, dailyPrice: input.dailyPrice, weekendPrice: input.weekendPrice ?? null } }); }
  async createRentalService(ctx: TenantContext, input: CreateRentalServiceInput) { return this.prisma.rentalService.create({ data: { businessId: ctx.businessId, attractionId: input.attractionId, name: input.name, type: input.type, revenueCategoryId: input.revenueCategoryId, dailyPrice: input.dailyPrice, weekendPrice: input.weekendPrice ?? null, seasonalPrice: input.seasonalPrice ?? null, seasonalStartsOn: input.seasonalStartsOn ?? null, seasonalEndsOn: input.seasonalEndsOn ?? null } }); }
  async createTenantRental(ctx: TenantContext, input: CreateTenantRentalInput) { return this.prisma.tenantRental.create({ data: { businessId: ctx.businessId, attractionId: input.attractionId, tenantName: input.tenantName, revenueCategoryId: input.revenueCategoryId, rentalPrice: input.rentalPrice } }); }
  async findAttraction(ctx: TenantContext, id: string) { return this.prisma.attraction.findFirst({ where: { businessId: ctx.businessId, id } }); }
  async findTicketType(ctx: TenantContext, id: string) { return this.prisma.ticketType.findFirst({ where: { businessId: ctx.businessId, id } }); }
  async findTicketPackage(ctx: TenantContext, id: string) { return this.prisma.ticketPackage.findFirst({ where: { businessId: ctx.businessId, id } }); }
  async findParkingService(ctx: TenantContext, id: string) { return this.prisma.parkingService.findFirst({ where: { businessId: ctx.businessId, id } }); }
  async findRentalService(ctx: TenantContext, id: string) { return this.prisma.rentalService.findFirst({ where: { businessId: ctx.businessId, id } }); }
  async findTenantRental(ctx: TenantContext, id: string) { return this.prisma.tenantRental.findFirst({ where: { businessId: ctx.businessId, id } }); }
  async countVisitors(ctx: TenantContext, attractionId: string, date: Date): Promise<number> { const agg = await this.prisma.visitorTransaction.aggregate({ where: { businessId: ctx.businessId, attractionId, transactionDate: date, status: { in: ["DRAFT", "PAID"] } }, _sum: { visitorCount: true } }); return agg._sum.visitorCount ?? 0; }
  async nextTransactionNumber(ctx: TenantContext, date: Date): Promise<string> { const prefix = "VIS-" + date.getUTCFullYear() + String(date.getUTCMonth() + 1).padStart(2, "0") + "-"; const latest = await this.prisma.visitorTransaction.findFirst({ where: { businessId: ctx.businessId, transactionNumber: { startsWith: prefix } }, orderBy: { transactionNumber: "desc" } }); const next = latest ? Number(latest.transactionNumber.slice(prefix.length)) + 1 : 1; return prefix + String(next).padStart(5, "0"); }
  async createVisitorTransaction(ctx: TenantContext, input: CreateVisitorTransactionInput & { transactionNumber: string; unitPrice: bigint; amount: bigint; quantity: number; visitorCount: number; validationCode: string; receiptNumber: string; revenueCategoryId: string; qrPayload: Record<string, unknown> }): Promise<VisitorTransaction> { const row = await this.prisma.visitorTransaction.create({ data: { businessId: ctx.businessId, transactionNumber: input.transactionNumber, status: "DRAFT", source: input.source, transactionDate: input.transactionDate, attractionId: input.attractionId, ticketTypeId: input.ticketTypeId ?? null, ticketPackageId: input.ticketPackageId ?? null, parkingServiceId: input.parkingServiceId ?? null, rentalServiceId: input.rentalServiceId ?? null, tenantRentalId: input.tenantRentalId ?? null, cashAccountId: input.cashAccountId, quantity: input.quantity, visitorCount: input.visitorCount, unitPrice: input.unitPrice, amount: input.amount, validationCode: input.validationCode, receiptNumber: input.receiptNumber, qrPayload: input.qrPayload as Prisma.InputJsonValue, bookingReference: input.bookingReference ?? null, createdByUserId: ctx.actorUserId } }); return row as VisitorTransaction; }
  async findVisitorTransaction(ctx: TenantContext, id: string) { const row = await this.prisma.visitorTransaction.findFirst({ where: { businessId: ctx.businessId, id } }); return row as VisitorTransaction | null; }
  async findVisitorTransactionByValidationCode(ctx: TenantContext, code: string) { const row = await this.prisma.visitorTransaction.findFirst({ where: { businessId: ctx.businessId, validationCode: code } }); return row as VisitorTransaction | null; }
  async markPaid(ctx: TenantContext, id: string, revenueTransactionId: string) { const row = await this.prisma.visitorTransaction.update({ where: { id, businessId: ctx.businessId }, data: { status: "PAID", revenueTransactionId, paidAt: new Date() } }); return row as VisitorTransaction; }
  async markVoided(ctx: TenantContext, id: string, reason: string) { const row = await this.prisma.visitorTransaction.update({ where: { id, businessId: ctx.businessId }, data: { status: "VOID", voidReason: reason, voidedAt: new Date() } }); return row as VisitorTransaction; }
  async createAuditLog(ctx: TenantContext, event: TourismAuditEvent): Promise<void> { await this.prisma.auditLog.create({ data: { businessId: ctx.businessId, actorUserId: ctx.actorUserId, action: event.action, entityType: event.entityType, entityId: event.entityId ?? null, metadata: event.metadata as Prisma.InputJsonValue, requestId: ctx.requestId ?? null, ipAddress: ctx.ipAddress ?? null, userAgent: ctx.userAgent ?? null } }); }
}

