export interface NavItem { title: string; href: string; icon?: string; group?: string; children?: NavItem[]; }

export const NAV_GROUPS = ["Utama", "Operasional", "Keuangan", "Pembukuan", "Sistem"] as const;

export const navigation: NavItem[] = [
  { title: "Dashboard", href: "/dashboard", icon: "dashboard", group: "Utama", children: [
    { title: "Ringkasan", href: "/dashboard" }, { title: "Analitik Penjualan", href: "/dashboard/sales" }, { title: "Analitik Stok", href: "/dashboard/inventory" }, { title: "Analitik Kas", href: "/dashboard/cash" }, { title: "Analitik Saldo Rekanan", href: "/dashboard/float" }, { title: "Analitik Pelanggan", href: "/dashboard/customers" }, { title: "Analitik Pemasok", href: "/dashboard/vendors" }
  ] },
  { title: "Scan Laporan Harian", href: "/sales/scan", icon: "scan", group: "Utama" },
  { title: "Kasir (POS)", href: "/pos", icon: "pos", group: "Operasional", children: [{ title: "Kasir", href: "/pos" }, { title: "Sesi Kasir", href: "/pos/sessions" }, { title: "Struk", href: "/pos/receipts" }, { title: "Tutup Kasir", href: "/pos/closing" }] },
  { title: "Penjualan", href: "/sales/orders", icon: "sales", group: "Operasional", children: [{ title: "Penjualan Harian", href: "/sales/orders" }, { title: "Pembayaran", href: "/sales/payments" }, { title: "Pelanggan", href: "/sales/customers" }] },
  { title: "Pembelian", href: "/purchase/orders", icon: "purchase", group: "Operasional", children: [{ title: "Pesanan Pembelian", href: "/purchase/orders" }, { title: "Penerimaan Barang", href: "/purchase/receipts" }, { title: "Retur Pembelian", href: "/purchase/returns" }, { title: "Tagihan Pemasok", href: "/purchase/vendor-bills" }] },
  { title: "Produk & Stok", href: "/inventory/products", icon: "inventory", group: "Operasional", children: [{ title: "Produk", href: "/inventory/products" }, { title: "Kategori", href: "/inventory/categories" }, { title: "Saldo Stok", href: "/inventory/balances" }, { title: "Mutasi Stok", href: "/inventory/movements" }, { title: "Penyesuaian Stok", href: "/inventory/adjustments" }, { title: "Transfer Stok", href: "/inventory/transfers" }] },
  { title: "Kas & Bank", href: "/cash/transactions", icon: "cash", group: "Keuangan", children: [{ title: "Transaksi Kas", href: "/cash/transactions" }, { title: "Sesi Kas", href: "/cash/sessions" }, { title: "Transfer Kas", href: "/cash/transfers" }, { title: "Rekonsiliasi", href: "/cash/reconciliation" }] },
  { title: "Piutang & Utang", href: "/ar-ap/invoices", icon: "arap", group: "Keuangan", children: [{ title: "Faktur (Invoice)", href: "/ar-ap/invoices" }, { title: "Tagihan", href: "/ar-ap/bills" }, { title: "Piutang", href: "/ar-ap/receivables" }, { title: "Utang", href: "/ar-ap/payables" }, { title: "Cicilan", href: "/installments" }, { title: "Kontak", href: "/contacts" }] },
  { title: "Saldo Rekanan", href: "/float/accounts", icon: "float", group: "Keuangan", children: [{ title: "Akun Rekanan", href: "/float/accounts" }, { title: "Isi Saldo", href: "/float/top-up" }, { title: "Pemakaian", href: "/float/consume" }, { title: "Transfer Saldo", href: "/float/transfers" }, { title: "Penyesuaian", href: "/float/adjustments" }, { title: "Snapshot Saldo", href: "/float/snapshots" }] },
  { title: "Akuntansi", href: "/accounting/journals", icon: "accounting", group: "Pembukuan", children: [{ title: "Jurnal", href: "/accounting/journals" }, { title: "Bagan Akun (COA)", href: "/accounting/chart-of-accounts" }, { title: "Periode Fiskal", href: "/accounting/fiscal-periods" }, { title: "Saldo Awal", href: "/accounting/beginning-balances" }, { title: "Audit", href: "/accounting/audit" }] },
  { title: "Laporan", href: "/reports/general-ledger", icon: "reports", group: "Pembukuan", children: [{ title: "Buku Besar", href: "/reports/general-ledger" }, { title: "Buku Pembantu", href: "/reports/subsidiary-ledger" }, { title: "Neraca Saldo", href: "/reports/trial-balance" }, { title: "Laba Rugi", href: "/reports/profit-loss" }, { title: "Neraca", href: "/reports/balance-sheet" }, { title: "Arus Kas", href: "/reports/cash-flow" }, { title: "Laporan Penjualan", href: "/reports/sales" }, { title: "Laporan Pembelian", href: "/reports/purchase" }, { title: "Laporan Stok", href: "/reports/inventory" }, { title: "Laporan Saldo Rekanan", href: "/reports/float" }] },
  { title: "Pengaturan", href: "/settings", icon: "settings", group: "Sistem", children: [{ title: "Profil Usaha", href: "/settings" }, { title: "Anggota Tim", href: "/settings/members" }] },
  { title: "Organisasi", href: "/organizations", icon: "settings", group: "Sistem" },
  { title: "Admin (God Mode)", href: "/admin", icon: "admin", group: "Sistem", children: [{ title: "Panel Admin", href: "/admin" }, { title: "Reset Data", href: "/admin/reset" }, { title: "Changelog", href: "/admin/changelog" }] },
];
