export interface NavItem { title: string; href: string; children?: NavItem[]; }

export const navigation: NavItem[] = [
  { title: "Dashboard", href: "/dashboard", children: [
    { title: "Overview", href: "/dashboard" }, { title: "Sales Analytics", href: "/dashboard/sales" }, { title: "Inventory Analytics", href: "/dashboard/inventory" }, { title: "Cash Analytics", href: "/dashboard/cash" }, { title: "Float Analytics", href: "/dashboard/float" }, { title: "Customer Analytics", href: "/dashboard/customers" }, { title: "Vendor Analytics", href: "/dashboard/vendors" }
  ] },
  { title: "POS", href: "/pos", children: [{ title: "Register", href: "/pos" }, { title: "Sessions", href: "/pos/sessions" }, { title: "Receipts", href: "/pos/receipts" }, { title: "Closing", href: "/pos/closing" }] },
  { title: "Sales", href: "/sales/orders", children: [{ title: "Orders", href: "/sales/orders" }, { title: "Payments", href: "/sales/payments" }, { title: "Customers", href: "/sales/customers" }] },
  { title: "Purchase", href: "/purchase/orders", children: [{ title: "Orders", href: "/purchase/orders" }, { title: "Receipts", href: "/purchase/receipts" }, { title: "Returns", href: "/purchase/returns" }, { title: "Vendor Bills", href: "/purchase/vendor-bills" }] },
  { title: "Inventory", href: "/inventory/products", children: [{ title: "Products", href: "/inventory/products" }, { title: "Categories", href: "/inventory/categories" }, { title: "Balances", href: "/inventory/balances" }, { title: "Movements", href: "/inventory/movements" }, { title: "Adjustments", href: "/inventory/adjustments" }, { title: "Transfers", href: "/inventory/transfers" }] },
  { title: "Cash", href: "/cash/transactions", children: [{ title: "Transactions", href: "/cash/transactions" }, { title: "Sessions", href: "/cash/sessions" }, { title: "Transfers", href: "/cash/transfers" }, { title: "Reconciliation", href: "/cash/reconciliation" }] },
  { title: "AR/AP", href: "/ar-ap/invoices", children: [{ title: "Invoices", href: "/ar-ap/invoices" }, { title: "Bills", href: "/ar-ap/bills" }, { title: "Receivables", href: "/ar-ap/receivables" }, { title: "Payables", href: "/ar-ap/payables" }, { title: "Customers", href: "/ar-ap/customers" }, { title: "Vendors", href: "/ar-ap/vendors" }] },
  { title: "Float", href: "/float/accounts", children: [{ title: "Accounts", href: "/float/accounts" }, { title: "Top Up", href: "/float/top-up" }, { title: "Consume", href: "/float/consume" }, { title: "Transfers", href: "/float/transfers" }, { title: "Adjustments", href: "/float/adjustments" }, { title: "Snapshots", href: "/float/snapshots" }] },
  { title: "Accounting", href: "/accounting/journals", children: [{ title: "Journals", href: "/accounting/journals" }, { title: "Chart of Accounts", href: "/accounting/chart-of-accounts" }, { title: "Fiscal Periods", href: "/accounting/fiscal-periods" }, { title: "Beginning Balances", href: "/accounting/beginning-balances" }, { title: "Audit", href: "/accounting/audit" }] },
  { title: "Reports", href: "/reports/general-ledger", children: [{ title: "General Ledger", href: "/reports/general-ledger" }, { title: "Trial Balance", href: "/reports/trial-balance" }, { title: "Profit & Loss", href: "/reports/profit-loss" }, { title: "Balance Sheet", href: "/reports/balance-sheet" }, { title: "Cash Flow", href: "/reports/cash-flow" }, { title: "Sales", href: "/reports/sales" }, { title: "Purchase", href: "/reports/purchase" }, { title: "Inventory", href: "/reports/inventory" }, { title: "Float", href: "/reports/float" }] },
  { title: "Settings", href: "/settings" }
];
