import { Prisma, PrismaClient } from "@prisma/client";
import { AccountGroupCode, AccountSnapshot } from "../../accounting/domain/accounting-types";
import { ArApAuditEvent, ArApRepository } from "../application/ar-ap-repository";
import { ApplyCreditNoteInput, Bill, CreateBillInput, CreateCustomerInput, CreateInvoiceInput, CreateVendorInput, Customer, Invoice, Payment, RecordPaymentInput, TenantContext, Vendor } from "../domain/ar-ap-types";
import type { TxClient } from "../../shared/tx";
const g={ASSET:1,LIABILITY:2,EQUITY:3,REVENUE:4,COGS:5,EXPENSE:6,OTHER_EXPENSE:7} as const;
export class PrismaArApRepository implements ArApRepository{constructor(private prisma:PrismaClient){}
 private db(tx?:TxClient){return (tx as Prisma.TransactionClient) ?? this.prisma;}
async findAccount(ctx:TenantContext,id:string):Promise<AccountSnapshot|null>{const a=await this.prisma.account.findFirst({where:{businessId:ctx.businessId,id}});return a?{id:a.id,businessId:a.businessId,code:a.code,name:a.name,groupCode:g[a.groupCode] as AccountGroupCode,normalBalance:a.normalBalance,subtype:a.subtype,isPostingAllowed:a.isPostingAllowed,isActive:a.isActive}:null}
async createCustomer(ctx:TenantContext,i:CreateCustomerInput):Promise<Customer>{return this.prisma.customer.create({data:{businessId:ctx.businessId,name:i.name,email:i.email??null,phone:i.phone??null,address:i.address??null}})} async createVendor(ctx:TenantContext,i:CreateVendorInput):Promise<Vendor>{return this.prisma.vendor.create({data:{businessId:ctx.businessId,name:i.name,email:i.email??null,phone:i.phone??null,address:i.address??null}})}
async findCustomer(ctx:TenantContext,id:string){return this.prisma.customer.findFirst({where:{businessId:ctx.businessId,id}})} async findVendor(ctx:TenantContext,id:string){return this.prisma.vendor.findFirst({where:{businessId:ctx.businessId,id}})}
async nextInvoiceNumber(ctx:TenantContext,d:Date){return this.next(ctx,'INV',d)} async nextBillNumber(ctx:TenantContext,d:Date){return this.next(ctx,'BILL',d)} async nextPaymentNumber(ctx:TenantContext,d:Date){return this.next(ctx,'PAY',d)} async nextNoteNumber(ctx:TenantContext,d:Date){return this.next(ctx,'NOTE',d)}
async createInvoice(ctx:TenantContext,i:CreateInvoiceInput,n:string):Promise<Invoice>{return this.prisma.invoice.create({data:{businessId:ctx.businessId,invoiceNumber:n,customerId:i.customerId,issueDate:i.issueDate,dueDate:i.dueDate,arAccountId:i.arAccountId,revenueAccountId:i.revenueAccountId,subtotal:i.subtotal,description:i.description,createdByUserId:ctx.actorUserId}})}
async createBill(ctx:TenantContext,i:CreateBillInput,n:string):Promise<Bill>{return this.prisma.bill.create({data:{businessId:ctx.businessId,billNumber:n,vendorId:i.vendorId,issueDate:i.issueDate,dueDate:i.dueDate,apAccountId:i.apAccountId,expenseAccountId:i.expenseAccountId,subtotal:i.subtotal,description:i.description,createdByUserId:ctx.actorUserId}})}
async findInvoice(ctx:TenantContext,id:string){return this.prisma.invoice.findFirst({where:{businessId:ctx.businessId,id}})} async findBill(ctx:TenantContext,id:string){return this.prisma.bill.findFirst({where:{businessId:ctx.businessId,id}})}
async markInvoicePosted(ctx:TenantContext,id:string,j:string,tx?:TxClient):Promise<Invoice>{return this.db(tx).invoice.update({where:{id,businessId:ctx.businessId},data:{status:'POSTED',postedJournalId:j,postedByUserId:ctx.actorUserId,postedAt:new Date()}})} async markBillPosted(ctx:TenantContext,id:string,j:string,tx?:TxClient):Promise<Bill>{return this.db(tx).bill.update({where:{id,businessId:ctx.businessId},data:{status:'POSTED',postedJournalId:j,postedByUserId:ctx.actorUserId,postedAt:new Date()}})}
async createPayment(ctx:TenantContext,i:RecordPaymentInput&{direction:'CUSTOMER_PAYMENT'|'VENDOR_PAYMENT';paymentNumber:string;postedJournalId:string;customerId?:string|null;vendorId?:string|null},tx?:TxClient):Promise<Payment>{return this.db(tx).payment.create({data:{businessId:ctx.businessId,paymentNumber:i.paymentNumber,direction:i.direction,invoiceId:i.invoiceId??null,billId:i.billId??null,customerId:i.customerId??null,vendorId:i.vendorId??null,paymentDate:i.paymentDate,cashAccountId:i.cashAccountId,amount:i.amount,description:i.description,postedJournalId:i.postedJournalId,createdByUserId:ctx.actorUserId}})}
async updateInvoicePaid(ctx:TenantContext,id:string,paidAmount:bigint,status:Invoice['status'],tx?:TxClient):Promise<Invoice>{return this.db(tx).invoice.update({where:{id,businessId:ctx.businessId},data:{paidAmount,status}})} async updateBillPaid(ctx:TenantContext,id:string,paidAmount:bigint,status:Bill['status'],tx?:TxClient):Promise<Bill>{return this.db(tx).bill.update({where:{id,businessId:ctx.businessId},data:{paidAmount,status}})}
async createCreditNote(ctx:TenantContext,i:ApplyCreditNoteInput&{noteNumber:string;postedJournalId:string;customerId:string},tx?:TxClient){await this.db(tx).adjustmentNote.create({data:{businessId:ctx.businessId,noteNumber:i.noteNumber,type:'CREDIT_NOTE',invoiceId:i.invoiceId,customerId:i.customerId,noteDate:i.noteDate,amount:i.amount,description:i.description,postedJournalId:i.postedJournalId,createdByUserId:ctx.actorUserId}})}
async listInvoices(ctx:TenantContext){return this.prisma.invoice.findMany({where:{businessId:ctx.businessId}})} async listBills(ctx:TenantContext){return this.prisma.bill.findMany({where:{businessId:ctx.businessId}})}
async createAuditLog(ctx:TenantContext,e:ArApAuditEvent){await this.prisma.auditLog.create({data:{businessId:ctx.businessId,actorUserId:ctx.actorUserId,action:e.action,entityType:e.entityType,entityId:e.entityId??null,metadata:e.metadata as Prisma.InputJsonValue,requestId:ctx.requestId??null,ipAddress:ctx.ipAddress??null,userAgent:ctx.userAgent??null}})}
private async next(ctx:TenantContext,prefix0:string,d:Date){const prefix=prefix0+'-'+d.getUTCFullYear()+String(d.getUTCMonth()+1).padStart(2,'0')+'-'; const table=prefix0==='INV'?'invoice':prefix0==='BILL'?'bill':prefix0==='NOTE'?'adjustmentNote':'payment'; const field=prefix0==='INV'?'invoiceNumber':prefix0==='BILL'?'billNumber':prefix0==='NOTE'?'noteNumber':'paymentNumber'; const latest=await (this.prisma[table as 'invoice'] as any).findFirst({where:{businessId:ctx.businessId,[field]:{startsWith:prefix}},orderBy:{[field]:'desc'}}); const next=latest?Number(latest[field].slice(prefix.length))+1:1; return prefix+String(next).padStart(5,'0')} }

