import { describe, expect, it } from "vitest";
import { JournalRepository, PostedJournalResult } from "../../src/features/accounting/application/journal-repository";
import { JournalPostingService } from "../../src/features/accounting/application/journal-posting-service";
import { AccountSnapshot, FiscalPeriodSnapshot, TenantContext as ATC, ValidatedJournal } from "../../src/features/accounting/domain/accounting-types";
import { FloatManagementService } from "../../src/features/float/application/float-service";
import { InventoryRepository, CreateCostHistoryRecord, CreateInventoryMovementRecord, InventoryAuditEvent } from "../../src/features/inventory/application/inventory-repository";
import { InventoryService } from "../../src/features/inventory/application/inventory-service";
import { CreateProductInput, InventoryBalanceEntity, InventoryMovementEntity, ProductCategoryEntity, ProductCostHistoryEntity, ProductEntity, ProductPriceEntity, ProviderProductEntity, TenantContext, UpdatePriceInput, UpdateProductInput } from "../../src/features/inventory/domain/inventory-types";

const accounts: AccountSnapshot[] = [
  { id: "inventory", businessId: "biz-1", code: "110601", name: "Persediaan", groupCode: 1, subtype: "inventory", normalBalance: "DEBIT", isPostingAllowed: true, isActive: true },
  { id: "cogs", businessId: "biz-1", code: "510101", name: "HPP", groupCode: 5, normalBalance: "DEBIT", isPostingAllowed: true, isActive: true },
  { id: "revenue", businessId: "biz-1", code: "410101", name: "Pendapatan", groupCode: 4, normalBalance: "CREDIT", isPostingAllowed: true, isActive: true },
  { id: "float-asset", businessId: "biz-1", code: "110301", name: "Float", groupCode: 1, subtype: "float", normalBalance: "DEBIT", isPostingAllowed: true, isActive: true },
  { id: "other-revenue", businessId: "biz-2", code: "410101", name: "Revenue 2", groupCode: 4, normalBalance: "CREDIT", isPostingAllowed: true, isActive: true }
];

class JR implements JournalRepository { posted: ValidatedJournal[] = []; async findAccountsForPosting(ctx: ATC, ids: string[]) { return accounts.filter((a) => a.businessId === ctx.businessId && ids.includes(a.id)); } async findOpenFiscalPeriod(ctx: ATC): Promise<FiscalPeriodSnapshot | null> { return { id: "p", businessId: ctx.businessId, startsOn: new Date("2026-01-01"), endsOn: new Date("2026-12-31"), isClosed: false }; } async findPostedJournalByIdempotencyKey() { return null; } async createPostedJournal(_: ATC, j: ValidatedJournal): Promise<PostedJournalResult> { this.posted.push(j); return { journalId: "j" + this.posted.length, journalNumber: "JV", postedAt: new Date(), totalDebit: j.totalDebit, totalCredit: j.totalCredit }; } async createAuditLog() {} }

class Repo implements InventoryRepository {
  categories = new Map<string, ProductCategoryEntity>(); products = new Map<string, ProductEntity>(); providers = new Map<string, ProviderProductEntity>(); prices: ProductPriceEntity[] = []; balances = new Map<string, InventoryBalanceEntity>(); movements: InventoryMovementEntity[] = []; histories: ProductCostHistoryEntity[] = []; audits: InventoryAuditEvent[] = []; seq = 1;
  async findAccounts(ctx: TenantContext, ids: string[]) { return accounts.filter((a) => a.businessId === ctx.businessId && ids.includes(a.id)); }
  async findCategory(ctx: TenantContext, id: string) { const c = this.categories.get(id); return c?.businessId === ctx.businessId ? c : null; }
  async createProduct(ctx: TenantContext, input: CreateProductInput) { const p: ProductEntity = { id: "prod" + this.seq++, businessId: ctx.businessId, type: input.type, sku: input.sku, name: input.name, categoryId: input.categoryId ?? null, inventoryAccountId: input.inventoryAccountId ?? null, cogsAccountId: input.cogsAccountId ?? null, revenueAccountId: input.revenueAccountId, trackStock: input.trackStock ?? input.type === "PHYSICAL", isActive: true }; this.products.set(p.id, p); return p; }
  async updateProduct(ctx: TenantContext, id: string, input: UpdateProductInput) { const existing = this.products.get(id)!; const p: ProductEntity = { ...existing, type: input.type, sku: input.sku, name: input.name, categoryId: input.categoryId ?? null, inventoryAccountId: input.inventoryAccountId ?? null, cogsAccountId: input.cogsAccountId ?? null, revenueAccountId: input.revenueAccountId, trackStock: input.trackStock ?? input.type === "PHYSICAL" }; this.products.set(id, p); return p; }
  async findProduct(ctx: TenantContext, id: string) { const p = this.products.get(id); return p?.businessId === ctx.businessId ? p : null; }
  async listProducts(ctx: TenantContext) { return [...this.products.values()].filter((p) => p.businessId === ctx.businessId); }
  async listCategories(ctx: TenantContext) { return [...this.categories.values()].filter((c) => c.businessId === ctx.businessId); }
  async createProviderProduct(ctx: TenantContext, input: { productId: string; provider: string; providerSku: string; floatAccountId: string; dynamicBuyPrice?: bigint; dynamicSellPrice?: bigint }) { const pp: ProviderProductEntity = { id: "provider" + this.seq++, businessId: ctx.businessId, productId: input.productId, provider: input.provider as ProviderProductEntity["provider"], providerSku: input.providerSku, floatAccountId: input.floatAccountId, dynamicBuyPrice: input.dynamicBuyPrice ?? null, dynamicSellPrice: input.dynamicSellPrice ?? null, isActive: true }; this.providers.set(pp.id, pp); return pp; }
  async findProviderProduct(ctx: TenantContext, productId: string, providerProductId?: string) { return [...this.providers.values()].find((p) => p.businessId === ctx.businessId && p.productId === productId && (!providerProductId || p.id === providerProductId)) ?? null; }
  async createPrice(ctx: TenantContext, input: UpdatePriceInput) { const price: ProductPriceEntity = { id: "price" + this.seq++, businessId: ctx.businessId, productId: input.productId, priceType: input.priceType, amount: input.amount, effectiveDate: input.effectiveDate, priority: input.priority ?? 0, isActive: true }; this.prices.push(price); return price; }
  async findActivePrice(ctx: TenantContext, productId: string, priceType: "BUY" | "SELL", asOf: Date) { return this.prices.filter((p) => p.businessId === ctx.businessId && p.productId === productId && p.priceType === priceType && p.effectiveDate <= asOf && p.isActive).sort((a, b) => b.effectiveDate.getTime() - a.effectiveDate.getTime())[0] ?? null; }
  async listPrices(ctx: TenantContext, productId: string) { return this.prices.filter((p) => p.businessId === ctx.businessId && p.productId === productId); }
  async createCostHistory(ctx: TenantContext, input: CreateCostHistoryRecord) { const h: ProductCostHistoryEntity = { id: "hist" + this.seq++, businessId: ctx.businessId, productId: input.productId, previousCost: input.previousCost ?? 0n, buyPrice: input.buyPrice, sellPrice: input.sellPrice ?? null, marginAmount: input.marginAmount ?? null, marginRateBps: input.marginRateBps ?? null, effectiveDate: input.effectiveDate, source: input.source }; this.histories.push(h); return h; }
  async listCostHistory(ctx: TenantContext, productId: string) { return this.histories.filter((h) => h.businessId === ctx.businessId && h.productId === productId); }
  async findBalance(ctx: TenantContext, productId: string, locationId: string) { const b = this.balances.get(productId + ":" + locationId); return b?.businessId === ctx.businessId ? b : null; }
  async listBalances(ctx: TenantContext) { return [...this.balances.values()].filter((b) => b.businessId === ctx.businessId); }
  async listMovements(ctx: TenantContext, type?: InventoryMovementEntity["type"]) { return this.movements.filter((m) => m.businessId === ctx.businessId && (type ? m.type === type : true)); }
  async upsertBalance(ctx: TenantContext, balance: InventoryBalanceEntity) { const b = { ...balance, id: balance.id || "bal" + this.seq++ }; this.balances.set(balance.productId + ":" + balance.locationId, b); return b; }
  async atomicStockIn(ctx: TenantContext, productId: string, locationId: string, quantity: bigint, unitCost: bigint) { const key = productId + ":" + locationId; const current = this.balances.get(key) ?? { id: "bal" + this.seq++, businessId: ctx.businessId, productId, locationId, quantity: 0n, averageCost: 0n, inventoryValue: 0n }; const incomingValue = quantity * unitCost; const nextQty = current.quantity + quantity; const nextValue = current.inventoryValue + incomingValue; const avgCost = nextQty === 0n ? 0n : nextValue / nextQty; const b = { ...current, quantity: nextQty, averageCost: avgCost, inventoryValue: nextValue }; this.balances.set(key, b); return b; }
  async atomicStockOut(ctx: TenantContext, productId: string, locationId: string, quantity: bigint) { const key = productId + ":" + locationId; const current = this.balances.get(key)!; const totalCost = quantity * current.averageCost; const nextQty = current.quantity - quantity; const nextValue = current.inventoryValue - totalCost; const b = { ...current, quantity: nextQty, inventoryValue: nextValue < 0n ? 0n : nextValue, averageCost: nextQty === 0n ? 0n : current.averageCost }; this.balances.set(key, b); return b; }
  async createMovement(ctx: TenantContext, input: CreateInventoryMovementRecord) { const m: InventoryMovementEntity = { id: "mov" + this.seq++, ...input, postedJournalId: input.postedJournalId ?? null }; this.movements.push(m); return m; }
  async createAuditLog(_: TenantContext, e: InventoryAuditEvent) { this.audits.push(e); }
}

class FakeFloatService { calls: Array<{ amount: bigint; floatAccountId: string; expenseAccountId?: string }> = []; async consumeFloat(command: { amount: bigint; floatAccountId: string; expenseAccountId?: string }) { this.calls.push(command); return { journal: { journalId: "float-journal" }, transaction: {}, preview: {} }; } }

function setup() { const repo = new Repo(); const jr = new JR(); const float = new FakeFloatService(); const service = new InventoryService(repo, new JournalPostingService(jr), float as unknown as FloatManagementService); return { repo, jr, float, service }; }
const base = { businessId: "biz-1", actorUserId: "user" };
async function physical(service: InventoryService) { return service.createProduct({ ...base, type: "PHYSICAL", sku: "SKU-1", name: "Barang", inventoryAccountId: "inventory", cogsAccountId: "cogs", revenueAccountId: "revenue" }); }
async function digital(service: InventoryService) { return service.createProduct({ ...base, type: "DIGITAL", sku: "PLN100", name: "PLN 100", cogsAccountId: "cogs", revenueAccountId: "revenue", provider: "FASTPAY", providerSku: "PLN100", floatAccountId: "float-1", buyPrice: 98500n, sellPrice: 100000n }); }

describe("InventoryService", () => {
  it("records stock movement", async () => { const { service } = setup(); const p = await physical(service); const r = await service.stockIn({ ...base, productId: p.id, locationId: "main", movementDate: new Date("2026-05-30"), quantity: 10n, unitCost: 1000n, description: "Purchase" }); expect(r.balance.quantity).toBe(10n); expect(r.movement.type).toBe("STOCK_IN"); });
  it("calculates average cost", async () => { const { service } = setup(); const p = await physical(service); await service.stockIn({ ...base, productId: p.id, locationId: "main", movementDate: new Date("2026-05-30"), quantity: 10n, unitCost: 1000n, description: "A" }); const r = await service.stockIn({ ...base, productId: p.id, locationId: "main", movementDate: new Date("2026-05-31"), quantity: 10n, unitCost: 2000n, description: "B" }); expect(r.balance.averageCost).toBe(1500n); });
  it("keeps price history", async () => { const { repo, service } = setup(); const p = await physical(service); await service.updatePrice({ ...base, productId: p.id, priceType: "BUY", amount: 1000n, effectiveDate: new Date("2026-05-01") }); await service.updatePrice({ ...base, productId: p.id, priceType: "SELL", amount: 1500n, effectiveDate: new Date("2026-05-01") }); const history = await repo.listCostHistory({ businessId: "biz-1", actorUserId: "user" }, p.id); expect(history.at(-1)?.marginAmount).toBe(500n); });
  it("supports multiple active prices", async () => { const { repo, service } = setup(); const p = await physical(service); await service.updatePrice({ ...base, productId: p.id, priceType: "SELL", amount: 1000n, effectiveDate: new Date("2026-01-01") }); await service.updatePrice({ ...base, productId: p.id, priceType: "SELL", amount: 1200n, effectiveDate: new Date("2026-06-01") }); expect(await repo.listPrices({ businessId: "biz-1", actorUserId: "user" }, p.id)).toHaveLength(2); });
  it("consumes float for digital product cost", async () => { const { float, service } = setup(); const p = await digital(service); const r = await service.consumeDigitalProduct({ ...base, productId: p.id, transactionDate: new Date("2026-05-30"), quantity: 1n, description: "PLN sold" }); expect(r.movement.totalCost).toBe(98500n); expect(float.calls[0]).toMatchObject({ amount: 98500n, floatAccountId: "float-1", expenseAccountId: "cogs" }); });
  it("isolates tenants", async () => { const { service } = setup(); await expect(service.createProduct({ businessId: "biz-1", actorUserId: "user", type: "SERVICE", sku: "SVC", name: "Bad", revenueAccountId: "other-revenue" })).rejects.toThrow(/not found/i); const p = await physical(service); await expect(service.getInventoryBalance({ businessId: "biz-2", actorUserId: "user", productId: p.id, locationId: "main" })).resolves.toMatchObject({ quantity: 0n }); await expect(service.stockIn({ businessId: "biz-2", actorUserId: "user", productId: p.id, locationId: "main", movementDate: new Date(), quantity: 1n, unitCost: 1n, description: "leak" })).rejects.toThrow(/not found/i); });
});
