import { RevenueService } from "../../revenue/application/revenue-service";
import { TourismEngine } from "../domain/tourism-engine";
import { CreateVisitorTransactionInput, TenantContext, TourismError, VisitorTransactionSource } from "../domain/tourism-types";
import { CreateAttractionCommand, CreateParkingServiceCommand, CreateRentalServiceCommand, CreateTenantRentalCommand, CreateTicketPackageCommand, CreateTicketTypeCommand, CreateVisitorTransactionCommand, TourismAuditEvent, TourismRepository, ValidateTicketCommand, VoidVisitorTransactionCommand } from "./tourism-repository";

export class TourismService {
  constructor(private readonly repository: TourismRepository, private readonly revenueService: RevenueService, private readonly engine = new TourismEngine()) {}
  async createAttraction(command: CreateAttractionCommand) { const ctx = this.contextFrom(command); const row = await this.repository.createAttraction(ctx, command); await this.audit(ctx, "ATTRACTION_CREATED", "attraction", row.id, { name: row.name }); return row; }
  async createTicketType(command: CreateTicketTypeCommand) { const ctx = this.contextFrom(command); await this.requireAttraction(ctx, command.attractionId); const row = await this.repository.createTicketType(ctx, command); await this.audit(ctx, "TICKET_TYPE_CREATED", "ticket_type", row.id, { name: row.name }); return row; }
  async createTicketPackage(command: CreateTicketPackageCommand) { const ctx = this.contextFrom(command); await this.requireAttraction(ctx, command.attractionId); const row = await this.repository.createTicketPackage(ctx, command); await this.audit(ctx, "TICKET_PACKAGE_CREATED", "ticket_package", row.id, { name: row.name }); return row; }
  async createParkingService(command: CreateParkingServiceCommand) { const ctx = this.contextFrom(command); await this.requireAttraction(ctx, command.attractionId); const row = await this.repository.createParkingService(ctx, command); await this.audit(ctx, "PARKING_SERVICE_CREATED", "parking_service", row.id, { name: row.name }); return row; }
  async createRentalService(command: CreateRentalServiceCommand) { const ctx = this.contextFrom(command); await this.requireAttraction(ctx, command.attractionId); const row = await this.repository.createRentalService(ctx, command); await this.audit(ctx, "RENTAL_SERVICE_CREATED", "rental_service", row.id, { name: row.name, type: row.type }); return row; }
  async createTenantRental(command: CreateTenantRentalCommand) { const ctx = this.contextFrom(command); await this.requireAttraction(ctx, command.attractionId); const row = await this.repository.createTenantRental(ctx, command); await this.audit(ctx, "TENANT_RENTAL_CREATED", "tenant_rental", row.id, { tenantName: row.tenantName }); return row; }

  async createVisitorTransaction(command: CreateVisitorTransactionCommand) {
    const ctx = this.contextFrom(command);
    const pricing = await this.price(ctx, command);
    const number = await this.repository.nextTransactionNumber(ctx, command.transactionDate);
    const validationCode = this.engine.validationCode(number);
    const receiptNumber = this.engine.receiptNumber(number);
    const draft = await this.repository.createVisitorTransaction(ctx, { ...command, transactionNumber: number, unitPrice: pricing.unitPrice, amount: pricing.amount, quantity: pricing.quantity, visitorCount: pricing.visitorCount, validationCode, receiptNumber, revenueCategoryId: pricing.revenueCategoryId, qrPayload: { pending: true, validationCode } });
    const revenueDraft = await this.revenueService.createDraft({ businessId: ctx.businessId, actorUserId: ctx.actorUserId, type: pricing.revenueType, transactionDate: command.transactionDate, categoryId: pricing.revenueCategoryId, cashAccountId: command.cashAccountId, quantity: pricing.quantity, unitPrice: pricing.unitPrice, description: this.description(command.source, draft.transactionNumber) });
    const posted = await this.revenueService.post({ businessId: ctx.businessId, actorUserId: ctx.actorUserId, transactionId: revenueDraft.id });
    const paid = await this.repository.markPaid(ctx, draft.id, posted.transaction.id);
    await this.audit(ctx, "VISITOR_TRANSACTION_PAID", "visitor_transaction", paid.id, { transactionNumber: paid.transactionNumber, amount: paid.amount.toString(), revenueTransactionId: posted.transaction.id });
    return paid;
  }

  async validateTicket(command: ValidateTicketCommand) { const ctx = this.contextFrom(command); const tx = await this.repository.findVisitorTransactionByValidationCode(ctx, command.validationCode); const result = this.engine.validateTicket(tx); await this.audit(ctx, "TICKET_VALIDATED", "visitor_transaction", tx?.id, { validationCode: command.validationCode, valid: result.valid, reason: result.reason }); return result; }
  async voidVisitorTransaction(command: VoidVisitorTransactionCommand) { const ctx = this.contextFrom(command); if (command.reason.trim().length < 10) throw new TourismError("VOID_REASON_TOO_SHORT", "Void reason must be at least 10 characters."); const tx = await this.repository.findVisitorTransaction(ctx, command.visitorTransactionId); if (!tx) throw new TourismError("VISITOR_TRANSACTION_NOT_FOUND", "Visitor transaction was not found."); if (tx.status !== "PAID" || !tx.revenueTransactionId) throw new TourismError("ONLY_PAID_CAN_BE_VOIDED", "Only paid visitor transactions can be voided."); await this.revenueService.void({ businessId: ctx.businessId, actorUserId: ctx.actorUserId, transactionId: tx.revenueTransactionId, reason: command.reason }); const voided = await this.repository.markVoided(ctx, tx.id, command.reason.trim()); await this.audit(ctx, "VISITOR_TRANSACTION_VOIDED", "visitor_transaction", voided.id, { reason: command.reason.trim() }); return voided; }

  private async price(ctx: TenantContext, input: CreateVisitorTransactionInput) { const [attraction, ticketType, ticketPackage, parkingService, rentalService, tenantRental, usedVisitors] = await Promise.all([this.repository.findAttraction(ctx, input.attractionId), input.ticketTypeId ? this.repository.findTicketType(ctx, input.ticketTypeId) : Promise.resolve(null), input.ticketPackageId ? this.repository.findTicketPackage(ctx, input.ticketPackageId) : Promise.resolve(null), input.parkingServiceId ? this.repository.findParkingService(ctx, input.parkingServiceId) : Promise.resolve(null), input.rentalServiceId ? this.repository.findRentalService(ctx, input.rentalServiceId) : Promise.resolve(null), input.tenantRentalId ? this.repository.findTenantRental(ctx, input.tenantRentalId) : Promise.resolve(null), this.repository.countVisitors(ctx, input.attractionId, input.transactionDate)]); return this.engine.price(input, { attraction, ticketType, ticketPackage, parkingService, rentalService, tenantRental, usedVisitors }); }
  private async requireAttraction(ctx: TenantContext, id: string) { const attraction = await this.repository.findAttraction(ctx, id); if (!attraction) throw new TourismError("ATTRACTION_NOT_FOUND", "Attraction was not found."); return attraction; }
  private description(source: VisitorTransactionSource, number: string): string { return source.replace(/_/g, " ") + " " + number; }
  private async audit(ctx: TenantContext, action: Parameters<TourismRepository["createAuditLog"]>[1]["action"], entityType: Parameters<TourismRepository["createAuditLog"]>[1]["entityType"], entityId: string | undefined, metadata: Record<string, unknown>) { const event: TourismAuditEvent = { action, businessId: ctx.businessId, actorUserId: ctx.actorUserId, entityType, metadata }; if (entityId !== undefined) event.entityId = entityId; await this.repository.createAuditLog(ctx, event); }
  private contextFrom(command: { businessId: string; actorUserId: string; requestId?: string; ipAddress?: string; userAgent?: string }): TenantContext { const ctx: TenantContext = { businessId: command.businessId, actorUserId: command.actorUserId }; if (command.requestId !== undefined) ctx.requestId = command.requestId; if (command.ipAddress !== undefined) ctx.ipAddress = command.ipAddress; if (command.userAgent !== undefined) ctx.userAgent = command.userAgent; return ctx; }
}

