import { AccountSnapshot } from "../../accounting/domain/accounting-types";
import { CashError, CashJournalPreview, CashMovementType, CashSessionEntity, CashValidationContext, CloseSessionInput, OpenSessionInput, RecordCashMovementInput, ReconcileCashInput, TransferCashInput } from "./cash-types";

export class CashEngine {
  previewOpen(input: OpenSessionInput, context: CashValidationContext): CashJournalPreview {
    if (input.openingAmount < 0n) throw new CashError("INVALID_OPENING_AMOUNT", "Opening amount cannot be negative.");
    this.assertDrawer(context, input.businessId); this.assertCash(context.drawer!.cashAccountId, context.cashAccount ?? null, input.businessId, "cashAccountId"); this.assertEquity(input.equityAccountId, context.equityAccount ?? null, input.businessId, "equityAccountId");
    return this.preview(input.businessId, input.openedAt, "CASH_OPENING_BALANCE", "Opening cash session", [this.line(context.cashAccount!, "DEBIT", input.openingAmount), this.line(context.equityAccount!, "CREDIT", input.openingAmount)]);
  }
  previewMovement(input: RecordCashMovementInput, context: CashValidationContext): CashJournalPreview {
    this.validateAmount(input.amount); this.assertCash(input.cashAccountId, context.cashAccount ?? null, input.businessId, "cashAccountId"); if (!input.description.trim()) throw new CashError("DESCRIPTION_REQUIRED", "Description is required.");
    if (input.type === "EXPENSE" || input.type === "WITHDRAWAL") { this.assertPosting(input.categoryAccountId ?? "", context.categoryAccount ?? null, input.businessId, "categoryAccountId"); return this.preview(input.businessId, input.movementDate, "CASH_" + input.type, input.description, [this.line(context.categoryAccount!, "DEBIT", input.amount), this.line(context.cashAccount!, "CREDIT", input.amount)]); }
    if (input.type === "SALE_RECEIPT" || input.type === "CUSTOMER_DEPOSIT") { this.assertPosting(input.categoryAccountId ?? "", context.categoryAccount ?? null, input.businessId, "categoryAccountId"); return this.preview(input.businessId, input.movementDate, "CASH_" + input.type, input.description, [this.line(context.cashAccount!, "DEBIT", input.amount), this.line(context.categoryAccount!, "CREDIT", input.amount)]); }
    if (input.type === "ADJUSTMENT") { this.assertPosting(input.categoryAccountId ?? "", context.categoryAccount ?? null, input.businessId, "categoryAccountId"); return this.preview(input.businessId, input.movementDate, "CASH_ADJUSTMENT", input.description, [this.line(context.cashAccount!, "DEBIT", input.amount), this.line(context.categoryAccount!, "CREDIT", input.amount)]); }
    throw new CashError("UNSUPPORTED_MOVEMENT_TYPE", "Movement type must use the dedicated service or is unsupported.", { type: input.type });
  }
  previewTransfer(input: TransferCashInput, context: CashValidationContext): CashJournalPreview { this.validateAmount(input.amount); this.assertCash(input.sourceCashAccountId, context.cashAccount ?? null, input.businessId, "sourceCashAccountId"); this.assertCash(input.destinationCashAccountId, context.destinationCashAccount ?? null, input.businessId, "destinationCashAccountId"); if (input.sourceCashAccountId === input.destinationCashAccountId) throw new CashError("TRANSFER_SAME_ACCOUNT", "Source and destination cash accounts must be different."); return this.preview(input.businessId, input.movementDate, "CASH_TRANSFER", input.description, [this.line(context.destinationCashAccount!, "DEBIT", input.amount), this.line(context.cashAccount!, "CREDIT", input.amount)]); }
  previewClose(input: CloseSessionInput, context: CashValidationContext): { preview: CashJournalPreview | null; differenceAmount: bigint } { const session = this.assertOpenSession(context, input.businessId); if (input.countedAmount < 0n) throw new CashError("INVALID_COUNT", "Counted amount cannot be negative."); const diff = input.countedAmount - session.expectedClosingAmount; if (diff === 0n) return { preview: null, differenceAmount: diff }; return { preview: this.previewDifference(input.businessId, input.closedAt, session.cashAccountId, diff, context), differenceAmount: diff }; }
  previewReconcile(input: ReconcileCashInput, context: CashValidationContext): { preview: CashJournalPreview | null; differenceAmount: bigint } { const session = context.session; if (!session || session.businessId !== input.businessId) throw new CashError("SESSION_NOT_FOUND", "Cash session was not found in this business."); const diff = input.countedAmount - session.expectedClosingAmount; if (diff === 0n) return { preview: null, differenceAmount: diff }; return { preview: this.previewDifference(input.businessId, input.reconciledAt, session.cashAccountId, diff, context), differenceAmount: diff }; }
  expectedAfter(type: CashMovementType, current: bigint, amount: bigint): bigint { if (["OPENING_BALANCE", "SALE_RECEIPT", "CUSTOMER_DEPOSIT", "ADJUSTMENT"].includes(type)) return current + amount; if (["EXPENSE", "WITHDRAWAL", "TRANSFER", "CLOSING"].includes(type)) return current - amount; return current; }
  private previewDifference(businessId: string, date: Date, cashAccountId: string, diff: bigint, context: CashValidationContext): CashJournalPreview { this.assertCash(cashAccountId, context.cashAccount ?? null, businessId, "cashAccountId"); this.assertPosting("differenceAccountId", context.differenceAccount ?? null, businessId, "differenceAccountId"); const amount = diff < 0n ? -diff : diff; return diff > 0n ? this.preview(businessId, date, "CASH_DIFFERENCE", "Cash difference", [this.line(context.cashAccount!, "DEBIT", amount), this.line(context.differenceAccount!, "CREDIT", amount)]) : this.preview(businessId, date, "CASH_DIFFERENCE", "Cash difference", [this.line(context.differenceAccount!, "DEBIT", amount), this.line(context.cashAccount!, "CREDIT", amount)]); }
  private assertDrawer(context: CashValidationContext, businessId: string): void { if (!context.drawer || context.drawer.businessId !== businessId || !context.drawer.isActive) throw new CashError("DRAWER_NOT_AVAILABLE", "Cash drawer is not available in this business."); }
  private assertOpenSession(context: CashValidationContext, businessId: string): CashSessionEntity { const s = context.session; if (!s || s.businessId !== businessId) throw new CashError("SESSION_NOT_FOUND", "Cash session was not found in this business."); if (s.status !== "OPEN") throw new CashError("SESSION_NOT_OPEN", "Cash session is not open."); return s; }
  private validateAmount(amount: bigint): void { if (amount <= 0n) throw new CashError("INVALID_AMOUNT", "Amount must be greater than zero."); }
  private assertCash(id: string, account: AccountSnapshot | null, businessId: string, field: string): void { this.assertPosting(id, account, businessId, field); if (!account || account.groupCode !== 1 || (account.subtype !== "cash" && account.subtype !== "bank")) throw new CashError("ACCOUNT_NOT_CASH_OR_BANK", "Account must be cash or bank.", { accountId: id, field }); }
  private assertEquity(id: string, account: AccountSnapshot | null, businessId: string, field: string): void { this.assertPosting(id, account, businessId, field); if (!account || account.groupCode !== 3) throw new CashError("ACCOUNT_NOT_EQUITY", "Opening balance offset must be equity.", { accountId: id, field }); }
  private assertPosting(id: string, account: AccountSnapshot | null, businessId: string, field: string): void { if (!account) throw new CashError("ACCOUNT_NOT_FOUND", "Account was not found in this business.", { accountId: id, field }); if (account.businessId !== businessId) throw new CashError("TENANT_ACCOUNT_MISMATCH", "Account must belong to the same business."); if (!account.isActive || !account.isPostingAllowed) throw new CashError("ACCOUNT_NOT_POSTABLE", "Account must be active and posting-enabled."); }
  private preview(businessId: string, transactionDate: Date, source: string, description: string, lines: CashJournalPreview["lines"]): CashJournalPreview { const totalDebit = lines.filter((l) => l.side === "DEBIT").reduce((s, l) => s + l.amount, 0n); const totalCredit = lines.filter((l) => l.side === "CREDIT").reduce((s, l) => s + l.amount, 0n); return { businessId, transactionDate, source, description, lines, totalDebit, totalCredit }; }
  private line(account: AccountSnapshot, side: "DEBIT" | "CREDIT", amount: bigint) { return { accountId: account.id, side, amount, accountCode: account.code, accountName: account.name }; }
}
