export interface UiModuleRegistryItem {
  id: string;
  title: string;
  backendService: string;
  routes: string[];
  pages: string[];
  layouts: string[];
  forms: string[];
  dialogs: string[];
  drawers: string[];
  tables: string[];
  reports: string[];
  dashboards: string[];
}

export const uiModuleRegistry: UiModuleRegistryItem[] = [
  { id: "dashboard", title: "Dashboard Analytics", backendService: "DashboardService", routes: ["/dashboard", "/dashboard/sales", "/dashboard/inventory", "/dashboard/cash", "/dashboard/float", "/dashboard/customers", "/dashboard/vendors"], pages: ["Overview", "Sales Analytics", "Inventory Analytics", "Cash Analytics", "Float Analytics", "Customer Analytics", "Vendor Analytics"], layouts: ["DashboardGridLayout", "AnalyticsDetailLayout"], forms: ["DashboardFilterForm"], dialogs: [], drawers: ["KpiDrilldownDrawer"], tables: ["ExceptionListTable"], reports: [], dashboards: ["ExecutiveDashboard", "SalesDashboard", "InventoryDashboard", "CashDashboard", "FloatDashboard"] },
  { id: "accounting", title: "Accounting", backendService: "JournalPostingService, ChartOfAccountsService, BusinessService", routes: ["/accounting/journals", "/accounting/chart-of-accounts", "/accounting/fiscal-periods", "/accounting/beginning-balances", "/accounting/audit"], pages: ["Journal List", "Journal Detail", "Chart of Accounts", "Fiscal Periods", "Beginning Balances", "Audit Trail"], layouts: ["AccountingWorkspaceLayout"], forms: ["JournalEntryForm", "AccountForm", "FiscalPeriodForm", "BeginningBalanceForm"], dialogs: ["PostJournalDialog", "VoidJournalDialog", "ClosePeriodDialog", "ReopenPeriodDialog"], drawers: ["AccountPickerDrawer", "SourceTraceDrawer", "JournalPreviewDrawer"], tables: ["JournalTable", "JournalLinesTable", "ChartOfAccountsTreeTable", "AuditTable"], reports: ["JournalTraceReport"], dashboards: [] },
  { id: "ar-ap", title: "AR/AP", backendService: "ArApService", routes: ["/ar-ap/invoices", "/ar-ap/bills", "/ar-ap/receivables", "/ar-ap/payables", "/ar-ap/customers", "/ar-ap/vendors"], pages: ["Invoices", "Bills", "Receivables", "Payables", "Customers", "Vendors"], layouts: ["DocumentWorkspaceLayout"], forms: ["InvoiceForm", "BillForm", "CustomerForm", "VendorForm", "PaymentRecordForm", "CreditNoteForm"], dialogs: ["PostInvoiceDialog", "PostBillDialog", "ApplyCreditNoteDialog"], drawers: ["CustomerDrawer", "VendorDrawer", "AgingDrawer", "PaymentDrawer"], tables: ["InvoiceTable", "BillTable", "CustomerTable", "VendorTable", "AgingTable"], reports: ["ReceivableAging", "PayableAging"], dashboards: [] },
  { id: "payment", title: "Payment & Wallet", backendService: "PaymentService", routes: ["/sales/payments", "/wallets"], pages: ["Payments", "Customer Wallets"], layouts: ["PaymentWorkspaceLayout"], forms: ["PaymentForm", "AllocationForm", "WalletTopupForm", "WalletSpendForm", "WalletRefundForm", "WalletAdjustmentForm"], dialogs: ["SplitPaymentDialog", "AllocationPreviewDialog"], drawers: ["WalletMovementDrawer", "PaymentMethodDrawer"], tables: ["PaymentTable", "AllocationTable", "WalletHistoryTable"], reports: ["PaymentAllocationReport"], dashboards: [] },
  { id: "float", title: "Float Management", backendService: "FloatManagementService", routes: ["/float/accounts", "/float/top-up", "/float/consume", "/float/transfers", "/float/adjustments", "/float/snapshots"], pages: ["Float Accounts", "Top Up", "Consume", "Transfers", "Adjustments", "Snapshots"], layouts: ["FloatWorkspaceLayout"], forms: ["FloatAccountForm", "FloatTopupForm", "FloatConsumptionForm", "FloatTransferForm", "FloatAdjustmentForm", "FloatSnapshotForm"], dialogs: ["LowFloatThresholdDialog"], drawers: ["FloatAccountDrawer", "FloatTransactionDrawer"], tables: ["FloatAccountTable", "FloatTransactionTable", "FloatSnapshotTable"], reports: ["FloatReport"], dashboards: ["FloatAnalytics"] },
  { id: "inventory", title: "Inventory", backendService: "InventoryService", routes: ["/inventory/products", "/inventory/categories", "/inventory/balances", "/inventory/movements", "/inventory/adjustments", "/inventory/transfers"], pages: ["Products", "Categories", "Balances", "Movements", "Adjustments", "Transfers"], layouts: ["InventoryWorkspaceLayout"], forms: ["ProductForm", "CategoryForm", "PriceForm", "StockInForm", "StockOutForm", "AdjustmentForm", "TransferForm", "DigitalConsumptionForm"], dialogs: ["StockPreviewDialog"], drawers: ["ProductDetailDrawer", "CostHistoryDrawer", "MovementTraceDrawer"], tables: ["ProductTable", "InventoryBalanceTable", "InventoryMovementTable", "CostHistoryTable"], reports: ["InventoryReport"], dashboards: ["InventoryAnalytics"] },
  { id: "purchase", title: "Purchase", backendService: "PurchaseService", routes: ["/purchase/orders", "/purchase/receipts", "/purchase/returns", "/purchase/vendor-bills"], pages: ["Purchase Orders", "Receipts", "Returns", "Vendor Bills"], layouts: ["PurchaseWorkspaceLayout"], forms: ["PurchaseOrderForm", "ReceivePurchaseForm", "PurchaseReturnForm", "GenerateVendorBillForm"], dialogs: ["ApprovePurchaseDialog", "ReceivePreviewDialog"], drawers: ["PurchaseOrderDrawer", "ReceiptDrawer", "ReturnDrawer"], tables: ["PurchaseOrderTable", "ReceiptTable", "ReturnTable"], reports: ["PurchaseReport"], dashboards: [] },
  { id: "sales", title: "Sales", backendService: "SalesService", routes: ["/sales/orders", "/sales/payments", "/sales/customers"], pages: ["Sales Orders", "Payments", "Customers"], layouts: ["SalesWorkspaceLayout"], forms: ["SalesOrderForm", "SalesPaymentAllocationForm"], dialogs: ["ConfirmSaleDialog"], drawers: ["SalesOrderDrawer", "CustomerHistoryDrawer"], tables: ["SalesOrderTable", "SalesItemTable"], reports: ["SalesReport"], dashboards: ["SalesAnalytics"] },
  { id: "pos", title: "POS", backendService: "PosService", routes: ["/pos", "/pos/sessions", "/pos/receipts", "/pos/closing"], pages: ["Register", "Sessions", "Receipts", "Closing"], layouts: ["PosRegisterLayout", "PosSessionLayout"], forms: ["CartItemForm", "CheckoutForm", "CloseSessionForm"], dialogs: ["CustomerPickerDialog", "SplitPaymentDialog", "VoidTransactionDialog"], drawers: ["ProductSearchDrawer", "ReceiptDrawer", "ChangeToDepositDrawer"], tables: ["PosSessionTable", "ReceiptTable"], reports: ["PosSessionReport"], dashboards: [] },
  { id: "cash", title: "Cash Management", backendService: "CashManagementService, CashService", routes: ["/cash/transactions", "/cash/sessions", "/cash/transfers", "/cash/reconciliation"], pages: ["Transactions", "Sessions", "Transfers", "Reconciliation"], layouts: ["CashWorkspaceLayout"], forms: ["CashTransactionForm", "CashTransferForm", "OpenSessionForm", "CloseSessionForm", "ReconciliationForm", "ContactForm"], dialogs: ["PostCashDialog", "VoidCashDialog"], drawers: ["CashPreviewDrawer", "ContactDrawer"], tables: ["CashTransactionTable", "CashSessionTable", "ReconciliationTable"], reports: ["CashFlowReport"], dashboards: ["CashAnalytics"] },
  { id: "reporting", title: "Reporting", backendService: "ReportingService", routes: ["/reports/general-ledger", "/reports/trial-balance", "/reports/profit-loss", "/reports/balance-sheet", "/reports/cash-flow", "/reports/sales", "/reports/purchase", "/reports/inventory", "/reports/float"], pages: ["General Ledger", "Trial Balance", "Profit & Loss", "Balance Sheet", "Cash Flow", "Sales Report", "Purchase Report", "Inventory Report", "Float Report"], layouts: ["ReportWorkspaceLayout"], forms: ["ReportFilterForm"], dialogs: ["ExportReportDialog"], drawers: ["ReportDrilldownDrawer", "SourceTraceDrawer"], tables: ["ReportTable", "LedgerDrilldownTable"], reports: ["GeneralLedger", "TrialBalance", "ProfitLoss", "BalanceSheet", "CashFlow", "Sales", "Purchase", "Inventory", "Float"], dashboards: [] }
];

export function findUiModule(id: string): UiModuleRegistryItem | undefined { return uiModuleRegistry.find((item) => item.id === id); }
