import { PostJournalCommand } from "../../accounting/application/journal-repository";
import { JournalPostingService } from "../../accounting/application/journal-posting-service";
import { ArApEngine } from "../domain/ar-ap-engine";
import { ArApError, TenantContext } from "../domain/ar-ap-types";
import { AgingCommand, ApplyCreditNoteCommand, ArApRepository, CreateBillCommand, CreateCustomerCommand, CreateInvoiceCommand, CreateVendorCommand, RecordPaymentCommand } from "./ar-ap-repository";
export class ArApService {
 constructor(private readonly repo:ArApRepository, private readonly journal:JournalPostingService, private readonly engine=new ArApEngine()){}
 async createCustomer(c:CreateCustomerCommand){const ctx=this.ctx(c); if(!c.name.trim()) throw new ArApError('CUSTOMER_NAME_REQUIRED','Customer name is required.'); const row=await this.repo.createCustomer(ctx,c); await this.audit(ctx,'CUSTOMER_CREATED','customer',row.id,{name:row.name}); return row;}
 async createVendor(c:CreateVendorCommand){const ctx=this.ctx(c); if(!c.name.trim()) throw new ArApError('VENDOR_NAME_REQUIRED','Vendor name is required.'); const row=await this.repo.createVendor(ctx,c); await this.audit(ctx,'VENDOR_CREATED','vendor',row.id,{name:row.name}); return row;}
 async createInvoice(c:CreateInvoiceCommand){const ctx=this.ctx(c); this.engine.validateAmount(c.subtotal); const customer=await this.repo.findCustomer(ctx,c.customerId); if(!customer||!customer.isActive) throw new ArApError('CUSTOMER_NOT_AVAILABLE','Customer is not available.'); this.engine.validateInvoiceAccounts(await this.repo.findAccount(ctx,c.arAccountId),await this.repo.findAccount(ctx,c.revenueAccountId),ctx.businessId); const inv=await this.repo.createInvoice(ctx,c,await this.repo.nextInvoiceNumber(ctx,c.issueDate)); await this.audit(ctx,'INVOICE_DRAFTED','invoice',inv.id,{invoiceNumber:inv.invoiceNumber}); return inv;}
 async postInvoice(c:{businessId:string;invoiceId:string;actorUserId:string}){const ctx=this.ctx(c); const inv=await this.invoice(ctx,c.invoiceId); if(inv.status!=='DRAFT') throw new ArApError('ONLY_DRAFT_CAN_BE_POSTED','Only draft invoice can be posted.'); const j=await this.journal.post(this.postCmd(ctx,inv.issueDate,'INVOICE',inv.id,inv.description,[{accountId:inv.arAccountId,side:'DEBIT' as const,amount:inv.subtotal},{accountId:inv.revenueAccountId,side:'CREDIT' as const,amount:inv.subtotal}])); const posted=await this.repo.markInvoicePosted(ctx,inv.id,j.journalId); await this.audit(ctx,'INVOICE_POSTED','invoice',posted.id,{journalId:j.journalId}); return posted;}
 async createBill(c:CreateBillCommand){const ctx=this.ctx(c); this.engine.validateAmount(c.subtotal); const vendor=await this.repo.findVendor(ctx,c.vendorId); if(!vendor||!vendor.isActive) throw new ArApError('VENDOR_NOT_AVAILABLE','Vendor is not available.'); this.engine.validateBillAccounts(await this.repo.findAccount(ctx,c.apAccountId),await this.repo.findAccount(ctx,c.expenseAccountId),ctx.businessId); const bill=await this.repo.createBill(ctx,c,await this.repo.nextBillNumber(ctx,c.issueDate)); await this.audit(ctx,'BILL_DRAFTED','bill',bill.id,{billNumber:bill.billNumber}); return bill;}
 async postBill(c:{businessId:string;billId:string;actorUserId:string}){const ctx=this.ctx(c); const bill=await this.bill(ctx,c.billId); if(bill.status!=='DRAFT') throw new ArApError('ONLY_DRAFT_CAN_BE_POSTED','Only draft bill can be posted.'); const j=await this.journal.post(this.postCmd(ctx,bill.issueDate,'BILL',bill.id,bill.description,[{accountId:bill.expenseAccountId,side:'DEBIT' as const,amount:bill.subtotal},{accountId:bill.apAccountId,side:'CREDIT' as const,amount:bill.subtotal}])); const posted=await this.repo.markBillPosted(ctx,bill.id,j.journalId); await this.audit(ctx,'BILL_POSTED','bill',posted.id,{journalId:j.journalId}); return posted;}
 async recordPayment(c:RecordPaymentCommand){const ctx=this.ctx(c); this.engine.validateCash(await this.repo.findAccount(ctx,c.cashAccountId),ctx.businessId); if((c.invoiceId?1:0)+(c.billId?1:0)!==1) throw new ArApError('PAYMENT_TARGET_INVALID','Payment must target invoice or bill.'); if(c.invoiceId){const inv=await this.invoice(ctx,c.invoiceId); this.engine.validatePayment(inv,c.amount); const j=await this.journal.post(this.postCmd(ctx,c.paymentDate,'CUSTOMER_PAYMENT',inv.id,c.description,[{accountId:c.cashAccountId,side:'DEBIT' as const,amount:c.amount},{accountId:inv.arAccountId,side:'CREDIT' as const,amount:c.amount}])); const paid=inv.paidAmount+c.amount; const status=this.engine.nextStatus(inv.subtotal,paid); const p=await this.repo.createPayment(ctx,{...c,direction:'CUSTOMER_PAYMENT',paymentNumber:await this.repo.nextPaymentNumber(ctx,c.paymentDate),postedJournalId:j.journalId,customerId:inv.customerId}); await this.repo.updateInvoicePaid(ctx,inv.id,paid,status); await this.audit(ctx,'PAYMENT_RECORDED','payment',p.id,{amount:c.amount.toString()}); return p;} const bill=await this.bill(ctx,c.billId!); this.engine.validatePayment(bill,c.amount); const j=await this.journal.post(this.postCmd(ctx,c.paymentDate,'VENDOR_PAYMENT',bill.id,c.description,[{accountId:bill.apAccountId,side:'DEBIT' as const,amount:c.amount},{accountId:c.cashAccountId,side:'CREDIT' as const,amount:c.amount}])); const paid=bill.paidAmount+c.amount; const status=this.engine.nextStatus(bill.subtotal,paid); const p=await this.repo.createPayment(ctx,{...c,direction:'VENDOR_PAYMENT',paymentNumber:await this.repo.nextPaymentNumber(ctx,c.paymentDate),postedJournalId:j.journalId,vendorId:bill.vendorId}); await this.repo.updateBillPaid(ctx,bill.id,paid,status); await this.audit(ctx,'PAYMENT_RECORDED','payment',p.id,{amount:c.amount.toString()}); return p;}
 async applyCreditNote(c:ApplyCreditNoteCommand){const ctx=this.ctx(c); const inv=await this.invoice(ctx,c.invoiceId); this.engine.validatePayment({...inv, subtotal: inv.subtotal-inv.paidAmount, paidAmount:0n, status:'POSTED'}, c.amount); const j=await this.journal.post(this.postCmd(ctx,c.noteDate,'CREDIT_NOTE',inv.id,c.description,[{accountId:inv.revenueAccountId,side:'DEBIT' as const,amount:c.amount},{accountId:inv.arAccountId,side:'CREDIT' as const,amount:c.amount}])); await this.repo.createCreditNote(ctx,{...c,noteNumber:await this.repo.nextNoteNumber(ctx,c.noteDate),postedJournalId:j.journalId,customerId:inv.customerId}); const newTotal=inv.subtotal-c.amount; const status=this.engine.nextStatus(newTotal,inv.paidAmount); await this.repo.updateInvoicePaid(ctx,inv.id,inv.paidAmount,status); await this.audit(ctx,'CREDIT_NOTE_APPLIED','adjustment_note',inv.id,{amount:c.amount.toString()});}
 async agingReceivables(c:AgingCommand){return this.engine.aging(await this.repo.listInvoices(this.ctx(c)),c.asOf)} async agingPayables(c:AgingCommand){return this.engine.aging(await this.repo.listBills(this.ctx(c)),c.asOf)}
 private async invoice(ctx:TenantContext,id:string){const inv=await this.repo.findInvoice(ctx,id); if(!inv) throw new ArApError('INVOICE_NOT_FOUND','Invoice not found.'); return inv;} private async bill(ctx:TenantContext,id:string){const bill=await this.repo.findBill(ctx,id); if(!bill) throw new ArApError('BILL_NOT_FOUND','Bill not found.'); return bill;}
 private postCmd(ctx:TenantContext,date:Date,source:string,id:string,description:string,lines:PostJournalCommand['lines']):PostJournalCommand{return{businessId:ctx.businessId,actorUserId:ctx.actorUserId,transactionDate:date,source,sourceId:id,description,idempotencyKey:source+':'+ctx.businessId+':'+id+':'+lines.map(l=>l.side+l.accountId+l.amount).join('|'),lines}}
 private async audit(ctx:TenantContext,action:Parameters<ArApRepository['createAuditLog']>[1]['action'],entityType:Parameters<ArApRepository['createAuditLog']>[1]['entityType'],entityId:string,metadata:Record<string,unknown>){await this.repo.createAuditLog(ctx,{action,businessId:ctx.businessId,actorUserId:ctx.actorUserId,entityType,entityId,metadata})}
 private ctx(c:{businessId:string;actorUserId:string;requestId?:string;ipAddress?:string;userAgent?:string}):TenantContext{const ctx:TenantContext={businessId:c.businessId,actorUserId:c.actorUserId}; if(c.requestId!==undefined)ctx.requestId=c.requestId; if(c.ipAddress!==undefined)ctx.ipAddress=c.ipAddress; if(c.userAgent!==undefined)ctx.userAgent=c.userAgent; return ctx;}
}

