import { CashService } from "../../cash/application/cash-service";
import { PaymentService } from "../../payment/application/payment-service";
import { SalesService } from "../../sales/application/sales-service";
import { PosEngine } from "../domain/pos-engine";
import { cartItemToSalesItem, PosError, TenantContext } from "../domain/pos-types";
import { AddCartItemCommand, AllocatePosPaymentCommand, CheckoutTransactionCommand, ClosePosSessionCommand, OpenPosSessionCommand, PosRepository, RemoveCartItemCommand, SaveChangeAsDepositCommand, VoidTransactionCommand } from "./pos-repository";

export class PosService {
  constructor(private readonly repo: PosRepository, private readonly sales: SalesService, private readonly payment: PaymentService, private readonly cash: CashService, private readonly engine = new PosEngine()) {}
  async openPosSession(command: OpenPosSessionCommand) { const ctx = this.ctx(command); const terminal = await this.repo.findTerminal(ctx, command.terminalId); this.engine.validateOpen(terminal, ctx.businessId, command.openingAmount); if (await this.repo.findOpenSessionByTerminal(ctx, command.terminalId)) throw new PosError("POS_SESSION_ALREADY_OPEN", "Terminal already has an open POS session."); let cashSessionId: string | null = null; if (terminal?.cashDrawerId) { const cashOpenCommand = { businessId: ctx.businessId, actorUserId: ctx.actorUserId, drawerId: terminal.cashDrawerId, openedAt: command.openedAt, openingAmount: command.openingAmount, equityAccountId: command.equityAccountId }; if (command.shiftCode !== undefined) Object.assign(cashOpenCommand, { shiftCode: command.shiftCode }); const cashSession = await this.cash.openSession(cashOpenCommand); cashSessionId = cashSession.session.id; } const sessionInput = { terminalId: command.terminalId, openedAt: command.openedAt, openingAmount: command.openingAmount, cashSessionId }; if (command.shiftCode !== undefined) Object.assign(sessionInput, { shiftCode: command.shiftCode }); const session = await this.repo.createSession(ctx, sessionInput); await this.audit(ctx, "POS_SESSION_OPENED", "pos_session", session.id, { openingAmount: session.openingAmount.toString() }); return session; }
  async closePosSession(command: ClosePosSessionCommand) { const ctx = this.ctx(command); const session = this.engine.validateOpenSession(await this.repo.findSession(ctx, command.sessionId), ctx.businessId); if (session.cashSessionId) await this.cash.closeSession({ businessId: ctx.businessId, actorUserId: ctx.actorUserId, sessionId: session.cashSessionId, closedAt: command.closedAt, countedAmount: command.countedAmount, differenceAccountId: command.differenceAccountId }); const diff = command.countedAmount - session.expectedClosingAmount; const closed = await this.repo.closeSession(ctx, session.id, command.closedAt, command.countedAmount, diff); await this.audit(ctx, "POS_SESSION_CLOSED", "pos_session", session.id, { differenceAmount: diff.toString() }); return closed; }
  async addCartItem(command: AddCartItemCommand) { const ctx = this.ctx(command); const session = await this.repo.findSession(ctx, command.sessionId); this.engine.validateAddItem(command, session); const product = command.productId ? await this.repo.findProduct(ctx, command.productId) : await this.repo.findProductByBarcode(ctx, command.barcode!); if (!product) throw new PosError("PRODUCT_NOT_FOUND", "Product was not found in this business."); const tx = command.transactionId ? await this.repo.findTransaction(ctx, command.transactionId) : await this.repo.createTransaction(ctx, { sessionId: session!.id, customerId: command.customerId, transactionDate: command.requestId ? new Date() : new Date(), transactionNumber: await this.repo.nextTransactionNumber(ctx, new Date()) }); const item = await this.repo.addCartItem(ctx, tx!.id, command, product.id); const updated = await this.repo.findTransaction(ctx, tx!.id); const totals = this.engine.totals(updated!.items); await this.repo.updateTransactionTotals(ctx, tx!.id, totals); await this.audit(ctx, "POS_CART_UPDATED", "pos_transaction", tx!.id, { productId: product.id }); return { transaction: await this.repo.findTransaction(ctx, tx!.id), item }; }
  async removeCartItem(command: RemoveCartItemCommand) { const ctx = this.ctx(command); const tx = this.engine.validateDraft(await this.repo.findTransaction(ctx, command.transactionId), ctx.businessId); await this.repo.removeCartItem(ctx, tx.id, command.cartItemId); const updated = await this.repo.findTransaction(ctx, tx.id); await this.repo.updateTransactionTotals(ctx, tx.id, this.engine.totals(updated!.items)); return this.repo.findTransaction(ctx, tx.id); }
  async checkoutTransaction(command: CheckoutTransactionCommand) { const ctx = this.ctx(command); const tx = this.engine.validateDraft(await this.repo.findTransaction(ctx, command.transactionId), ctx.businessId); if (tx.items.length === 0) throw new PosError("CART_EMPTY", "Cannot checkout an empty cart."); const saleCommand = { businessId: ctx.businessId, actorUserId: ctx.actorUserId, customerId: tx.customerId, saleDate: command.saleDate, description: command.description, revenueSettlementAccountId: command.revenueSettlementAccountId, items: tx.items.map(cartItemToSalesItem) }; if (command.arAccountId !== undefined) Object.assign(saleCommand, { arAccountId: command.arAccountId }); const sale = await this.sales.createSalesOrder(saleCommand); const confirmed = await this.sales.confirmSalesOrder({ businessId: ctx.businessId, actorUserId: ctx.actorUserId, salesOrderId: sale.id }); const updated = await this.repo.updateTransactionStatus(ctx, tx.id, "CHECKOUT", 0n, 0n, confirmed.sale.id); await this.audit(ctx, "POS_TRANSACTION_CHECKED_OUT", "pos_transaction", tx.id, { salesOrderId: confirmed.sale.id }); return { transaction: updated, sale: confirmed }; }
  async allocatePayment(command: AllocatePosPaymentCommand) { const ctx = this.ctx(command); const tx = this.engine.validatePayable(await this.repo.findTransaction(ctx, command.transactionId), ctx.businessId); if (!tx.salesOrderId) throw new PosError("SALES_ORDER_REQUIRED", "Transaction must be checked out before payment."); const tendered = command.allocations.reduce((s, a) => s + a.amount, 0n); const due = tx.totalAmount - tx.paidAmount; const allocationAmount = tendered > due ? due : tendered; const change = tendered > due ? tendered - due : 0n; const allocations = this.trimAllocations(command.allocations, allocationAmount); const result = await this.sales.allocatePayment({ businessId: ctx.businessId, actorUserId: ctx.actorUserId, salesOrderId: tx.salesOrderId, allocations }); const receipt = result.sale.status === "PAID" ? await this.repo.createReceipt(ctx, tx.id, new Date(), tx.totalAmount, result.sale.paidAmount, change, await this.repo.nextReceiptNumber(ctx, new Date())) : null; const updated = await this.repo.updateTransactionStatus(ctx, tx.id, result.sale.status === "PAID" ? "PAID" : "PARTIALLY_PAID", result.sale.paidAmount, change, tx.salesOrderId, result.sale.paymentTransactionId ?? undefined, receipt?.id); if (change > 0n && command.changePolicy === "SAVE_TO_DEPOSIT") await this.saveChangeAsDeposit({ businessId: ctx.businessId, actorUserId: ctx.actorUserId, transactionId: tx.id, walletId: command.depositWalletId!, cashAccountId: command.depositCashAccountId! }); await this.audit(ctx, "POS_PAYMENT_ALLOCATED", "pos_transaction", tx.id, { paidAmount: updated.paidAmount.toString(), changeAmount: change.toString() }); return { transaction: updated, payment: result, receipt }; }
  async saveChangeAsDeposit(command: SaveChangeAsDepositCommand) { const ctx = this.ctx(command); const tx = await this.repo.findTransaction(ctx, command.transactionId); if (!tx || tx.changeAmount <= 0n) throw new PosError("NO_CHANGE_TO_SAVE", "Transaction has no change to save as deposit."); const result = await this.payment.topupWallet({ businessId: ctx.businessId, actorUserId: ctx.actorUserId, walletId: command.walletId, cashAccountId: command.cashAccountId, transactionDate: new Date(), amount: tx.changeAmount, description: "POS change deposit " + tx.transactionNumber }); await this.audit(ctx, "POS_CHANGE_SAVED_TO_DEPOSIT", "pos_transaction", tx.id, { amount: tx.changeAmount.toString() }); return result; }
  async voidTransaction(command: VoidTransactionCommand) { const ctx = this.ctx(command); const tx = await this.repo.findTransaction(ctx, command.transactionId); if (!tx) throw new PosError("POS_TRANSACTION_NOT_FOUND", "POS transaction was not found."); const updated = await this.repo.updateTransactionStatus(ctx, tx.id, "VOID"); await this.audit(ctx, "POS_TRANSACTION_VOIDED", "pos_transaction", tx.id, { reason: command.reason }); return updated; }
  private trimAllocations(allocations: import("../../payment/domain/payment-types").PaymentAllocationInput[], amount: bigint) { let remaining = amount; const out = []; for (const a of allocations) { if (remaining <= 0n) break; const used = a.amount > remaining ? remaining : a.amount; out.push({ ...a, amount: used }); remaining -= used; } return out; }
  private async audit(ctx: TenantContext, action: Parameters<PosRepository["createAuditLog"]>[1]["action"], entityType: Parameters<PosRepository["createAuditLog"]>[1]["entityType"], entityId: string, metadata: Record<string, unknown>) { await this.repo.createAuditLog(ctx, { action, businessId: ctx.businessId, actorUserId: ctx.actorUserId, entityType, entityId, metadata }); }
  private ctx(command: { businessId: string; actorUserId: string; requestId?: string; ipAddress?: string; userAgent?: string }): TenantContext { const ctx: TenantContext = { businessId: command.businessId, actorUserId: command.actorUserId }; if (command.requestId !== undefined) ctx.requestId = command.requestId; if (command.ipAddress !== undefined) ctx.ipAddress = command.ipAddress; if (command.userAgent !== undefined) ctx.userAgent = command.userAgent; return ctx; }
}
