import { AccountSnapshot } from "../../accounting/domain/accounting-types";
import { AgingBucket, ArApError, Bill, DocumentStatus, Invoice } from "./ar-ap-types";
export class ArApEngine {
  validateInvoiceAccounts(ar:AccountSnapshot|null,revenue:AccountSnapshot|null,businessId:string){this.assertAccount(ar,businessId,1,'AR account'); if (ar?.subtype && ar.subtype !== 'accounts_receivable') throw new ArApError('INVALID_AR_ACCOUNT','AR account must be accounts receivable.'); this.assertAccount(revenue,businessId,4,'Revenue account');}
  validateBillAccounts(ap:AccountSnapshot|null,expense:AccountSnapshot|null,businessId:string){this.assertAccount(ap,businessId,2,'AP account'); if (ap?.subtype && ap.subtype !== 'accounts_payable') throw new ArApError('INVALID_AP_ACCOUNT','AP account must be accounts payable.'); this.assertAccount(expense,businessId,6,'Expense account');}
  validateCash(cash:AccountSnapshot|null,businessId:string){this.assertAccount(cash,businessId,1,'Cash account'); if (cash?.subtype !== 'cash' && cash?.subtype !== 'bank') throw new ArApError('INVALID_CASH_ACCOUNT','Payment requires cash or bank account.');}
  validateAmount(amount:bigint){if(amount<=0n) throw new ArApError('INVALID_AMOUNT','Amount must be greater than zero.');}
  nextStatus(total:bigint, paid:bigint):DocumentStatus { if(paid===0n) return 'POSTED'; if(paid<total) return 'PARTIALLY_PAID'; if(paid===total) return 'PAID'; throw new ArApError('OVERPAYMENT','Paid amount cannot exceed document total.'); }
  validatePayment(document:Invoice|Bill, amount:bigint){this.validateAmount(amount); if(!['POSTED','PARTIALLY_PAID'].includes(document.status)) throw new ArApError('DOCUMENT_NOT_PAYABLE','Only posted or partially paid documents can be paid.'); const remaining=document.subtotal-document.paidAmount; if(amount>remaining) throw new ArApError('OVERPAYMENT','Payment cannot exceed outstanding balance.',{remaining:remaining.toString(),amount:amount.toString()});}
  aging<T extends {dueDate:Date; subtotal:bigint; paidAmount:bigint; status:DocumentStatus}>(docs:T[], asOf:Date):AgingBucket { const b={current:0n,days1To30:0n,days31To60:0n,days61To90:0n,over90:0n}; for(const d of docs){if(d.status==='PAID'||d.status==='VOID') continue; const outstanding=d.subtotal-d.paidAmount; if(outstanding<=0n) continue; const days=Math.floor((asOf.getTime()-d.dueDate.getTime())/(24*60*60*1000)); if(days<=0)b.current+=outstanding; else if(days<=30)b.days1To30+=outstanding; else if(days<=60)b.days31To60+=outstanding; else if(days<=90)b.days61To90+=outstanding; else b.over90+=outstanding;} return b;}
  private assertAccount(account:AccountSnapshot|null|undefined,businessId:string,group:number,label:string){if(!account) throw new ArApError('ACCOUNT_NOT_FOUND',label+' was not found.'); if(account.businessId!==businessId) throw new ArApError('TENANT_ACCOUNT_MISMATCH',label+' must belong to business.'); if(!account.isActive||!account.isPostingAllowed||account.groupCode!==group) throw new ArApError('INVALID_ACCOUNT',label+' has invalid type.');}
}

